### ISSUE TITLE
Error message `New(): invalid handle`

### ISSUE THREAD

**Issue by chrplr** [ardnew/ft232h#5]
Hello

I would like to use your module to read/write TTL signals on an Adafruit FT232H (despite your warning that the module is not ready for general use. Is GPIO support ok?)

I am using Linux (Ubuntu 22.04). Following the instructions in `README.md` I have blacklisted the ftdi driver 

When I plug the board, `lsusb` shows `Bus 001 Device 007: ID 0403:6014 Future Technology Devices International, Ltd FT232H Single HS USB-UART/FIFO IC`.
 
When I run `example/toggle.go`  I get an error message `New(): invalid handle`.

Passing `-h` or `-?` does not list command lines options.
 
I had a quick look at the source code and tried: `./toogle -index 1` which yields a different message (` device not found`) than `./toogle -index 0` (which yields `invalid handle`), so I guess that the board is detected.

Any suggestion?

Thank you for this module!

**Comment by ardnew** [comment]
Thanks for the feedback! It has admittedly been some time since I've even thought about this project, but vague error messages like that typically come from the native driver, i.e., `libftd2xx`, or from limited visibility into said driver. This driver is responsible for actually opening the device file descriptor and initializing the device.

I'll have time this weekend to try recreating and debugging this issue, but in the meantime my immediate suggestion would be to check device file permissions and udev configuration:

1. You said you blacklisted the USB serial driver — _and rebooted_, I presume — called`ftdi_sio` on Ubuntu. Good. 
	- After plugging in the device, you verified the output from `lsmod` does **not** include `"ftdi_sio"` ot `"ftdi"` anywhere?
2. Make sure udev (or your user account) are configured correctly. Based off [these Rust docs](https://docs.rs/libftd2xx/latest/libftd2xx/#udev-rules), and assuming you haven't modified the VID/PID of your device:
    > ## udev rules
    > To access the FTDI USB device as a regular user on Linux you need to update the <a href="https://en.wikipedia.org/wiki/Udev">udev</a> rules.
    >
    > Create a file called /etc/udev/rules.d/99-ftdi.rules with:
    > ```
    > SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666"
    > SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6010", MODE="0666"
    > SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6011", MODE="0666"
    > SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", MODE="0666"
    > SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", MODE="0666"
    > ```
    > Then, reload the rules:
    > ```
    > sudo udevadm control --reload-rules
    > sudo udevadm trigger 
    > ```

You can also check the [FTDI driver installation guide](http://www.ftdichip.cn/Support/Documents/AppNotes/AN_220_FTDI_Drivers_Installation_Guide_for_Linux.pdf) in case I've missed something. Otherwise, try searching the Web for `libftd2xx linux installation` or similar.

**Comment by gpallier** [comment]
Adding the udev rules worked.

Thanks *a lot*.

**Comment by chrplr** [comment]
Oops, I was logged with the wrong account (gpallier). I am closing this issue. Thanks again!
